apiVersion: v1
kind: Pod
metadata: 
  name: al-nafi-production-webapp
  labels:
    app: development
    tier: production
spec:
  containers:
  - name: production-webapp
    image: kodekloud/webapp-delayed-start
    ports:
      - containerPort: 8080
        protocol: TCP 
    env:
    - name: APP_START_DELAY
      value: "20"
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
  tolerations:
  - key: spray
    operator: Equal
    value: anti-insect
    effect: NoSchedule

