apiVersion: v1
kind: Service
metadata:
  name: alnafi-pod-service
  namespace: default
spec: 
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: production
  type: NodePort

