apiVersion: v1
kind: Pod
metadata:
  name: node-selector
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: node-selector
  dnsPolicy: ClusterFirst

  tolerations:
  - effect: NoSchedule
    key: spray
    operator: Equal
    value: anti-insect

  nodeSelector:
    size: medium
