apiVersion: v1
kind: Pod
metadata:
  name: sidecar-practice-pod
spec:
  containers:
  - name: main-container
    image: busybox:stable
    command: ['sh', '-c', 'echo "I am learning Kubernetes." > /write-dir/data.txt; while true; do sleep 5; done']
    volumeMounts:
    - name: shared-volume
      mountPath: /write-dir

  - name: sidecar-container
    image: busybox:stable
    command: ['sh','-c', 'while true; do cat /read-dir/data.txt; sleep 5;  done']
    volumeMounts:
    - name: shared-volume
      mountPath: /read-dir

  volumes:
  - name: shared-volume
    emptyDir: {}
