apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: dev
    tier: front-end
  name: testing
spec:
  containers:
  - image: alpine
    name: testing
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
